server.port=0
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=notification-group
app.kafka.topic.user-events=user-events
app.kafka.dlt-topic=user-events-DLT
spring.mail.host=mailpit
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
management.endpoints.web.exposure.include=health,info
logging.level.edu.example=DEBUG
eureka.client.serviceUrl.defaultZone=http://discovery-service:8761/eureka
